/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.81
 * Generated at: 2017-08-27 18:31:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import fjs.cs.action.form.EditForm;

public final class edit_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>AJAX based CRUD operations using jTable in Servlet and\r\n");
      out.write("\tJSP</title>\r\n");
      out.write("<!-- Include jTable script file. -->\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body bgcolor=\"CCFFFF\">\r\n");
      out.write("\t");

		EditForm form = (EditForm) request.getAttribute("editForm");
		String action = (String) request.getAttribute("action");
	
      out.write("\r\n");
      out.write("\t<form action=\"");
      out.print(action);
      out.write("\" method=\"post\" id=\"editForm\" name=\"Form\">\r\n");
      out.write("\t\t<div\r\n");
      out.write("\t\t\tstyle=\"width: 60%; margin-right: 20%; margin-left: 20%; text-align: center;\">\r\n");
      out.write("\t\t\t<h1 align=\"left\" style=\"color: red;\">Training</h1>\r\n");
      out.write("\t\t\t<hr>\r\n");
      out.write("\t\t\t<div id=\"center\">\r\n");
      out.write("\t\t\t\t<h4 align=\"left\"\">Login > Search Customer>Edit Customer Info</h4>\r\n");
      out.write("\t\t\t\t<div id=\"1\">\r\n");
      out.write("\t\t\t\t\t<table align=\"left\">\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td align=\"left\" width=\"95%;\"><h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t\tWellcome\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      out.print(request.getSession().getAttribute("username"));
      out.write("</h4></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><a href=\"login.jsp\">Log Out</a></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<br> <br>\r\n");
      out.write("\t\t\t\t<div style=\"background-color: blue;\">\r\n");
      out.write("\t\t\t\t\t<h4>\r\n");
      out.write("\t\t\t\t\t\t<p style=\"color: white;\" align=\"left\">Edit</p>\r\n");
      out.write("\t\t\t\t\t</h4>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div id=\"center\" width=\"70%\" height=\"25%\" cellpadding=\"5\"\r\n");
      out.write("\t\t\t\t\talign=\"center\" style=\"padding: 10%; font-weight: bold;\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<table cellpadding=\"10%;\">\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th colspan=\"2\"><h5 id=\"error\" style=\"color: red;\"></h5></th>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>Customer Id:</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><label >\r\n");
      out.write("\t\t\t\t\t\t\t\t");
if (form.getUserid() != 0) {
      out.write(' ');
      out.print(form.getUserid());
}
      out.write("</label></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>Customer Name:</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input type=\"text\" size=\"42%\" name=\"customerName\"\r\n");
      out.write("\t\t\t\t\t\t\t\t");
if (form.getCustomerName() != null) {
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\tvalue=\"");
      out.print(form.getCustomerName());
      out.write('"');
      out.write(' ');
}
      out.write("></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>Sex:</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td align=\"left\"><select name=\"sex\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"M\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");
      out.print(form.getSex().equals("M") ? "selected" : "");
      out.write(">M</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"F\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");
      out.print(form.getSex().equals("F") ? "selected" : "");
      out.write(">F</option>\r\n");
      out.write("\t\t\t\t\t\t\t</select></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>Birthday:</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input type=\"text\" size=\"42%\" name=\"birthDay\"\r\n");
      out.write("\t\t\t\t\t\t\t\t");
if (form.getBirthDay() != null) {
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\tvalue=\"");
      out.print(form.getBirthDay());
      out.write('"');
      out.write(' ');
}
      out.write("></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>Email:</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input type=\"text\" size=\"42%\" name=\"email\"\r\n");
      out.write("\t\t\t\t\t\t\t\t");
if (form.getEmail() != null) {
      out.write(" value=\"");
      out.print(form.getEmail());
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\t\t\t");
}
      out.write("></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>Address:</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input type=\"text\" style=\"padding: 7%;\" size=\"35%;\"\r\n");
      out.write("\t\t\t\t\t\t\t\tname=\"address\" ");
if (form.getAddress() != null) {
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\tvalue=\"");
      out.print(form.getAddress());
      out.write('"');
      out.write(' ');
}
      out.write("></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td colspan=\"2\" align=\"center\"><input type=\"submit\"\r\n");
      out.write("\t\t\t\t\t\t\t\tvalue=\"Save\"> ");

 	if (action.equals("processAdd.do")) {
 
      out.write(" <input\r\n");
      out.write("\t\t\t\t\t\t\t\ttype=\"button\" id=\"add\" value=\"Clear\"> ");

 	} else {
 
      out.write(" <input\r\n");
      out.write("\t\t\t\t\t\t\t\ttype=\"button\" id=\"edit\" value=\"Clear\"> ");

 	}
 
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div id=\"footer\" style=\"width: 100%; text-align: left;\">\r\n");
      out.write("\t\t\t\t\t<hr>\r\n");
      out.write("\t\t\t\t\t<label>Copy right@ 2000-2008 FUJINET, All Rights Reserved.</label>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t</form>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\tfunction validate() {\r\n");
      out.write("\t\t\tif (document.Form.customerName.value === \"\"\r\n");
      out.write("\t\t\t\t\t|| document.Form.customerName.value === null) {\r\n");
      out.write("\t\t\t\talert(document.Form.customerName.value );\r\n");
      out.write("\t\t\t\tdocument.getElementById(\"error\").innerHTML = \"ユーザーIDを入力してください。1\";\r\n");
      out.write("\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\tif (document.Form.birthDay.value === \"\"\r\n");
      out.write("\t\t\t\t\t|| document.Form.birthDay.value === null) {\r\n");
      out.write("\t\t\t\tdocument.getElementById(\"error\").innerHTML = \"パスワードを入力してください。2\";\r\n");
      out.write("\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif (document.Form.email.value === \"\"\r\n");
      out.write("\t\t\t\t\t|| document.Form.email.value === null) {\r\n");
      out.write("\t\t\t\tdocument.getElementById(\"error\").innerHTML = \"パスワードを入力してください。3\";\r\n");
      out.write("\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif (document.Form.address.value === \"\"\r\n");
      out.write("\t\t\t\t\t|| document.Form.address.value === null) {\r\n");
      out.write("\t\t\t\tdocument.getElementById(\"error\").innerHTML = \"パスワードを入力してください。4\";\r\n");
      out.write("\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tvar rxDatePattern = /^\\d{4}\\-(0?[1-9]|1[012])\\-(0?[1-9]|[12][0-9]|3[01])$/;\r\n");
      out.write("\r\n");
      out.write("\t\t\tif (rxDatePattern.test(document.Form.birthDay.value) == false) {\r\n");
      out.write("\t\t\t\tdocument.getElementById(\"error\").innerHTML = \"誕生日が不正です。\";\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\tvar reg = /^([A-Za-z0-9_\\-\\.])+\\@([A-Za-z0-9_\\-\\.])+\\.([A-Za-z]{2,4})$/;\r\n");
      out.write("\r\n");
      out.write("\t\t\tif (reg.test(document.Form.email.value) == false) {\r\n");
      out.write("\t\t\t\tdocument.getElementById(\"error\").innerHTML = \"メールアドレスが不正です。\";\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\treturn (true);\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t$(\"#add\").click(function(event) {\r\n");
      out.write("\t\t\tdocument.Form.customerName.value = \"\";\r\n");
      out.write("\t\t\tdocument.Form.birthDay.value = \"\";\r\n");
      out.write("\t\t\tdocument.Form.email.value = \"\";\r\n");
      out.write("\t\t\tdocument.Form.address.value = \"\";\r\n");
      out.write("\t\t\tdocument.getElementById(\"error\").innerHTML = \"\";\r\n");
      out.write("\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$(\"#edit\").click(function(event) {\r\n");
      out.write("\t\t\twindow.location.reload();\r\n");
      out.write("\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$(\"#editForm\").submit(function(event) {\r\n");
      out.write("\t\t\treturn validate();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
