/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.81
 * Generated at: 2017-08-27 18:06:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>Login Page</title>\r\n");
      out.write("<link href=\"jtable.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<script src=\"//code.jquery.com/jquery-1.11.3.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body bgcolor=\"#2EFEF7\">\r\n");
      out.write("\t<form action=\"register1.do\" method=\"post\" id=\"formDemo\" name=\"MyForm\">\r\n");
      out.write("<div style=\"color:red\">\r\n");
      out.write("    </div>\r\n");
      out.write("\t\t<div id=\"header\">\r\n");
      out.write("\t\t\t<h1 style=\"color: red;\">Training</h1>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<hr>\r\n");
      out.write("\t\t<h3>Login</h3>\r\n");
      out.write("\t\t<div id=\"center\" style=\"padding-top: 5%; padding-bottom: 20%;\">\r\n");
      out.write("\t\t\t<table align=\"center\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th colspan=\"2\"><h1 style=\"color: BLUE;\">LOGIN</h1></th>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th colspan=\"2\"><h5 id=\"error\" style=\"color: red;\">");
 String error =(String)request.getAttribute("error"); 
      out.print(error != null? error : "");
      out.write("</h5></th>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>User Id:</td>\r\n");
      out.write("\t\t\t\t\t<td> <input type=\"text\" name=\"userId\" size=\"50\" maxlength=\"8\" /><br></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>Password:</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" name=\"password\" size=\"50\"maxlength=\"8\" /><br></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td colspan=\"2\" align=\"center\"><input type=\"submit\"\r\n");
      out.write("\t\t\t\t\t\tvalue=\"Login\"> <input type=\"button\" id=\"reset\"\r\n");
      out.write("\t\t\t\t\t\tvalue=\"Clear\"></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<hr>\r\n");
      out.write("\t\t<div id=\"footer\">\r\n");
      out.write("\t\t\t<label>Copy right@ 2000-2008 FUJINET, All Rights Reserved.</label>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</form>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t<!--\r\n");
      out.write("\t\t// Form validation code will come here.\r\n");
      out.write("\t\tfunction validate() {\r\n");
      out.write("\r\n");
      out.write("\t\t\tif (document.MyForm.userId.value === \"\"\r\n");
      out.write("\t\t\t\t\t|| document.MyForm.userId.value === null) {\r\n");
      out.write("\t\t\t\tdocument.getElementById(\"error\").innerHTML = \"ユーザーIDを入力してください。\";\r\n");
      out.write("\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif (document.MyForm.password.value === \"\"\r\n");
      out.write("\t\t\t\t\t|| document.MyForm.password.value === null) {\r\n");
      out.write("\t\t\t\tdocument.getElementById(\"error\").innerHTML = \"パスワードを入力してください。\";\r\n");
      out.write("\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\treturn (true);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t$(\"#reset\").click(function(event) {\r\n");
      out.write("\t\t\tdocument.MyForm.userId.value = \"\";\r\n");
      out.write("\t\t\tdocument.MyForm.password.value = \"\";\r\n");
      out.write("\t\t\tdocument.getElementById(\"error\").innerHTML = \"\";\r\n");
      out.write("\t\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$(\"#formDemo\").submit(function(event){\r\n");
      out.write("\t\t\treturn validate();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
